// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaProject.Database;

#nullable disable

namespace NinjaProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231010103512_Migration3")]
    partial class Migration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NinjaApplication.Models.Gear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int")
                        .HasColumnName("agility");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GoldValue")
                        .HasColumnType("int")
                        .HasColumnName("goldvalue");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int")
                        .HasColumnName("intelligence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Strength")
                        .HasColumnType("int")
                        .HasColumnName("strength");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("gear");
                });

            modelBuilder.Entity("NinjaApplication.Models.GearCategory", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("category");

                    b.HasKey("Category");

                    b.ToTable("gear_category");
                });

            modelBuilder.Entity("NinjaApplication.Models.InventoryItem", b =>
                {
                    b.Property<int>("NinjaId")
                        .HasColumnType("int")
                        .HasColumnName("ninja_id");

                    b.Property<int>("GearId")
                        .HasColumnType("int")
                        .HasColumnName("gear_id");

                    b.Property<int>("PricePaid")
                        .HasColumnType("int");

                    b.HasKey("NinjaId", "GearId");

                    b.HasIndex("GearId");

                    b.ToTable("inventory_item");
                });

            modelBuilder.Entity("NinjaApplication.Models.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gold")
                        .HasColumnType("int")
                        .HasColumnName("gold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ninja");
                });

            modelBuilder.Entity("NinjaApplication.Models.Gear", b =>
                {
                    b.HasOne("NinjaApplication.Models.GearCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Gear_GearCategory");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NinjaApplication.Models.InventoryItem", b =>
                {
                    b.HasOne("NinjaApplication.Models.Gear", "Gear")
                        .WithMany("Ninjas")
                        .HasForeignKey("GearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApplication.Models.Ninja", "Ninja")
                        .WithMany("Inventory")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gear");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApplication.Models.Gear", b =>
                {
                    b.Navigation("Ninjas");
                });

            modelBuilder.Entity("NinjaApplication.Models.Ninja", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
